---
- name: Install ElasticSearch Dependencies (For Ubuntu)
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
        - gpg-agent
        - curl  
        - procps
        - net-tools
        - gnupg
        - python3-apt
 
- name: Install Elasticsearch
  block:
    - name: elasticsearch-install | Import Elasticsearch GPG Key
      ansible.builtin.shell: "curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg"
- name: Add Elasticsearch APT Repository
  ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        state: present
        filename: "elastic-8.x.list"

- name: Update Elasticsearch Configuration file
  lineinfile:
    path: /etc/elasticsearch/midterm.yml
    regexp: " {{ item.regexp }}"
    line: " {{ item.line }}"

    loop:
      - { regexp: '^network\.host, line: network.host: {{ server}}' }
      - { regxp: '^ http\.port: ', line t: {{ elasticseach.http_port }} ''}

- name: Enable and Start Elasticsearch service 
  service:
    name: elasticsearch
    state: started
    enabled: yes

    